[project]
name = "rigpl_erpnext"
authors = [
    { name = "Rohit Industries Group Pvt Ltd", email = "aditya@rigpl.com"}
]
description = "ERPNext Customizations for RIGPL"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # Core dependencies
    "fedex @ git+https://github.com/python-fedex-devs/python-fedex.git",
    "html2text==2025.4.15",
]

[tool.setuptools]
packages = ["rigpl_erpnext"]

[tool.setuptools.package-data]
rigpl_erpnext = ["/*.html", "/*.js", "/*.json", "/*.md", "/*.css", "/*.txt"]
